[package]
name = "storage-proofs-zexe"
description = "Implementations of Proofs of Storage on Zexe."
version = "0.5.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>", "laser <l@s3r.com>", "porcuquine <porcuquine@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"
readme = "README.md"

[lib]
bench = false

[dependencies]
bitvec = "0.5"
rand = "0.4"
libc = "0.2"
merkletree = "0.7.1"
failure = "0.1"
byteorder = "1"
config = "0.9.3"
crossbeam-utils = "0.6"
itertools = "0.8"
lazy_static = "1.2"
memmap = "0.7"
num-bigint = "0.2"
num-traits = "0.2"
clap = "2"
colored = "1.6"
aes = "0.3"
block-modes = "0.3"
sha2 = "0.8"
pbr = "1.0"
tempfile = "3"
fs2 = "0.4"
rayon = "1.0.0"
serde = { version = "1.0", features = ["derive"]}
base64 = "0.10.0"
blake2b_simd = "0.5"
blake2s_simd = "0.5"
toml = "0.5"
log = "0.4.7"
pretty_env_logger = "0.3.0"
serde_json = "1.0"
dpc = { git = "https://github.com/filecoin-project/zexe", rev = "533a799" }
snark = { git = "https://github.com/filecoin-project/zexe", rev = "533a799" }
algebra = { git = "https://github.com/filecoin-project/zexe", rev = "533a799" }
snark-gadgets = { git = "https://github.com/filecoin-project/zexe", rev = "533a799" }

[features]
default = []
simd = []
asm = ["sha2/sha2-asm"]
disk-trees = []
big-sector-sizes-bench = []

[dev-dependencies]
proptest = "0.7"
criterion = "0.2"
pretty_assertions = "0.6.1"
